version: '3.9'

services:
  mongodb:
  image: mongod:7
  container_name: mongoDB
  ports: 
    - MONGO_INITDB_ROOT_USERNAME=admin
    - MONGO_INITDB_ROOT_PASSWORD=secret
  volumes: 
    - mongo-data:/data/db
  restart: always
  healthcheck:
    test: ["CMD", "mongosh", "--eval", "db.adminCommand(`ping`)"]
    interval: 10s
    timeout: 5s
    retries: 5
    start_period: 10s
  networks:
    - mongo-net
volumes:
  mongo-data:
networks:
  mongo-net:
    driver: bridge